# Generated by Django 4.2 on 2023-06-30 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='posted_on',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='image',
            name='status',
        ),
    ]
