# Generated by Django 4.2 on 2023-06-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0002_rename_posted_on_image_date_remove_image_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='myimage')),
                ('status', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
